version: '1.0'

services:
  mysql_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: Test1234
      MYSQL_DATABASE: tamirdoon
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin1234
    ports:
      - '3306:3306'
    volumes:
    - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
  backend-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mysql_db
    environment:
      PORT: 3000
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: tamirdoon
      DB_USERNAME: admin
      DB_PASSWORD: Admin1234
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
  frontend-service:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules